;;;; chickbbio.import.scm - GENERATED BY CHICKEN 4.8.0.4 -*- Scheme -*-

(eval '(import chicken scheme srfi-4 srfi-18 bind))
(##sys#register-compiled-module
  'chickbbio
  (list)
  '((lookup-gpio . chickbbio#lookup-gpio)
    (open-pin . chickbbio#open-pin)
    (close-pin . chickbbio#close-pin)
    (read-pin . chickbbio#read-pin)
    (write-pin . chickbbio#write-pin)
    (openI2C . chickbbio#openI2C)
    (writeByte . chickbbio#writeByte)
    (writeList . chickbbio#writeList))
  (list)
  (list))

;; END OF FILE
